"""
_backend.py
===========
Single source of truth for quarimo backend availability.

All backend detection logic lives here.  Every other module — kernel files,
``_forest.py``, ``conftest.py``, test files — imports from this module rather
than performing its own detection.

Design
------
``_BackendCapabilities`` is a lazy, cached capability object.  Each backend is
probed at most once per interpreter session via ``@cached_property``; the probe
runs only when first accessed, not at import time.

The module-level ``backends`` singleton is the intended entry point::

    from quarimo._backend import backends

    if backends.cuda:
        # GPU path
    elif backends.numba:
        # CPU-parallel path
    else:
        # Python fallback

Backend priority (ascending — ``backends.best()`` returns the last available):
    ``python`` < ``cpu-parallel`` < ``mlx`` < ``cuda``

This ordering reflects real hardware: CUDA on a dedicated NVIDIA GPU is the
fastest option; MLX on Apple Silicon (integrated GPU, Unified Memory) is the
Apple equivalent; cpu-parallel (Numba JIT + OpenMP) is next; pure Python is
always the baseline fallback.  On any given machine, ``cuda`` and ``mlx`` are
mutually exclusive in practice (Apple Silicon cannot run CUDA).

Toolchain inspection
--------------------
``backends.cuda_info`` and ``backends.mlx_info`` return ``CUDAToolchainInfo``
and ``MLXToolchainInfo`` dataclasses that capture version numbers, device
information, and any detected incompatibilities.  A brief summary is logged at
DEBUG level when the module loads; incompatibilities (driver/runtime version
mismatches, PTX version conflicts, probe kernel failures) are logged at
CRITICAL so they surface even without a configured logging handler.

Backward-compatible public API
-------------------------------
The module also exports thin-wrapper functions (``check_numba_available``,
``check_cuda_available``, ``get_available_backends``, etc.) so that existing
call sites keep working without changes.
"""

from __future__ import annotations

import logging
import platform
import re
import shutil
import subprocess
from dataclasses import dataclass, field
from functools import cached_property
from typing import List, Optional, Tuple

logger = logging.getLogger('quarimo.backend')

# ---------------------------------------------------------------------------
# Kernel implementation registry
# ---------------------------------------------------------------------------
# Maps kernel name → frozenset of backends with a full implementation.
# Update this as new backend kernels are added — nothing else needs changing.
KERNEL_IMPLEMENTATIONS: dict[str, frozenset[str]] = {
    "quartet_topology": frozenset({"python", "cpu-parallel", "cuda", "mlx"}),
}


# ============================================================================ #
# Toolchain information dataclasses                                             #
# ============================================================================ #


@dataclass
class CUDAToolchainInfo:
    """
    Version and compatibility snapshot of the CUDA / Numba / LLVM toolchain.

    Populated by ``_probe_cuda_toolchain()``.  Errors indicate incompatibilities
    that will prevent the CUDA backend from functioning; warnings are non-fatal
    (e.g. ptxas not on PATH).

    Attributes
    ----------
    available : bool
        True only if a probe kernel compiled and ran successfully end-to-end.
    numba_version : str or None
        Installed numba version string, or None if numba is not installed.
    llvmlite_version : str or None
        Installed llvmlite version string.  llvmlite provides the LLVM/NVPTX
        backend that generates PTX from numba-compiled kernels.
    llvm_version : str or None
        LLVM version bundled with llvmlite (e.g. ``"14.0.6"``).
    cuda_driver_version : (int, int) or None
        CUDA driver version reported by the kernel driver, as (major, minor).
        Must be >= cuda_runtime_version for forward compatibility.
    cuda_runtime_version : (int, int) or None
        CUDA runtime version in the active environment, as (major, minor).
    ptx_version : str or None
        PTX ISA ``.version`` from the compiled probe kernel (e.g. ``"8.5"``).
        Generated by llvmlite's NVPTX backend; must be supported by ptxas.
    ptxas_path : str or None
        Absolute path to the ``ptxas`` assembler found on PATH.
    ptxas_version : str or None
        First line of ``ptxas --version`` output.
    devices : list[dict]
        One entry per visible CUDA device: ``{"name": str, "compute_capability": (int, int)}``.
    errors : list[str]
        Incompatibilities that prevent the CUDA backend from functioning.
        Each entry is logged at CRITICAL level.
    warnings : list[str]
        Non-fatal issues.  Each entry is logged at WARNING level.
    """

    available: bool
    numba_version: str | None = None
    llvmlite_version: str | None = None
    llvm_version: str | None = None
    cuda_driver_version: tuple[int, int] | None = None
    cuda_runtime_version: tuple[int, int] | None = None
    ptx_version: str | None = None
    ptxas_path: str | None = None
    ptxas_version: str | None = None
    devices: list[dict] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


@dataclass
class MLXToolchainInfo:
    """
    Version and hardware snapshot of the MLX / Metal toolchain.

    Populated by ``_probe_mlx_toolchain()``.

    Attributes
    ----------
    available : bool
        True only if a probe computation ran successfully on the Metal GPU.
    mlx_version : str or None
        Installed mlx version string, or None if mlx is not installed.
    gpu_name : str or None
        Metal GPU device name (e.g. ``"Apple M3 Pro"``).
    memory_size : int or None
        Total unified memory in bytes as reported by Metal.
    metal_version : str or None
        Metal API version string from ``mx.metal.device_info()``.
    macos_version : str or None
        macOS version string (e.g. ``"14.5"``).
    errors : list[str]
        Incompatibilities that prevent the MLX backend from functioning.
    warnings : list[str]
        Non-fatal issues.
    """

    available: bool
    mlx_version: str | None = None
    gpu_name: str | None = None
    memory_size: int | None = None
    metal_version: str | None = None
    macos_version: str | None = None
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


# ============================================================================ #
# Toolchain probes                                                              #
# ============================================================================ #


def _probe_cuda_toolchain() -> CUDAToolchainInfo:
    """
    Collect CUDA / Numba / LLVM version information and verify end-to-end
    kernel compilation by compiling and running a trivial probe kernel.

    The probe proceeds step by step and stops early when a required component
    is absent.  Incompatibilities are recorded in ``errors``; non-fatal issues
    go into ``warnings``.  The returned object's ``available`` flag is True
    only if the probe kernel compiled and executed without error.
    """
    info = CUDAToolchainInfo(available=False)

    # ── numba ─────────────────────────────────────────────────────────────────
    try:
        import numba
        info.numba_version = numba.__version__
    except ImportError:
        return info  # numba not installed — not an error, just unavailable

    # ── llvmlite / LLVM ───────────────────────────────────────────────────────
    # llvmlite provides the NVPTX backend that generates PTX from numba kernels.
    # Its version (and the bundled LLVM version) determines which PTX ISA
    # version is emitted — a mismatch with the system ptxas is the most common
    # source of CUDA_ERROR_UNSUPPORTED_PTX_VERSION failures.
    try:
        import llvmlite
        info.llvmlite_version = llvmlite.__version__
    except ImportError as e:
        info.warnings.append(f"llvmlite not importable: {e}")

    try:
        import llvmlite.binding as llvm_binding
        info.llvm_version = ".".join(str(x) for x in llvm_binding.llvm_version_info[:3])
    except Exception as e:
        info.warnings.append(f"Could not read LLVM version from llvmlite.binding: {e}")

    # ── CUDA availability ──────────────────────────────────────────────────────
    try:
        from numba import cuda
        if not cuda.is_available():
            return info  # no GPU or driver — not an error
    except Exception as e:
        info.errors.append(f"numba.cuda import or availability check failed: {e}")
        return info

    # ── CUDA driver version ───────────────────────────────────────────────────
    try:
        from numba.cuda.cudadrv.driver import driver as _drv
        info.cuda_driver_version = _drv.get_version()
    except Exception as e:
        info.warnings.append(f"Could not query CUDA driver version: {e}")

    # ── CUDA runtime version ──────────────────────────────────────────────────
    try:
        from numba.cuda.cudadrv.runtime import runtime as _rt
        info.cuda_runtime_version = _rt.get_version()
    except Exception as e:
        info.warnings.append(f"Could not query CUDA runtime version: {e}")

    # ── Driver / runtime compatibility ────────────────────────────────────────
    if info.cuda_driver_version and info.cuda_runtime_version:
        dv = info.cuda_driver_version
        rv = info.cuda_runtime_version
        if dv < rv:
            info.errors.append(
                f"CUDA driver ({dv[0]}.{dv[1]}) is older than the runtime "
                f"({rv[0]}.{rv[1]}). The driver must be at least as new as "
                "the CUDA runtime. Upgrade the driver or install an older "
                "cuda-toolkit to match."
            )

    # ── GPU devices ───────────────────────────────────────────────────────────
    try:
        from numba import cuda
        for device in cuda.gpus:
            with device:
                name = device.name
                if isinstance(name, bytes):
                    name = name.decode()
                info.devices.append({
                    "name": name,
                    "compute_capability": device.compute_capability,
                })
    except Exception as e:
        info.warnings.append(f"Could not enumerate CUDA devices: {e}")

    # ── ptxas ─────────────────────────────────────────────────────────────────
    # ptxas assembles PTX into device binary (CUBIN).  Its version must be >=
    # the PTX ISA version emitted by llvmlite's NVPTX backend.
    ptxas_path = shutil.which("ptxas")
    if ptxas_path:
        info.ptxas_path = ptxas_path
        try:
            result = subprocess.run(
                [ptxas_path, "--version"],
                capture_output=True, text=True, timeout=5,
            )
            lines = (result.stdout + result.stderr).strip().splitlines()
            info.ptxas_version = lines[0] if lines else None
        except Exception as e:
            info.warnings.append(f"Could not run ptxas --version: {e}")
    else:
        info.warnings.append(
            "ptxas not found on PATH. Numba requires ptxas to assemble CUDA "
            "kernels. Add the CUDA toolkit bin directory to PATH (e.g. "
            "module load cuda, or set CUDA_HOME)."
        )

    # ── End-to-end probe kernel ───────────────────────────────────────────────
    # Compiling and executing a trivial kernel catches PTX version mismatches,
    # linker errors, and any other toolchain incompatibilities that only surface
    # at JIT-compile time — including CUDA_ERROR_UNSUPPORTED_PTX_VERSION, which
    # occurs when llvmlite emits a PTX ISA version newer than ptxas supports.
    try:
        import warnings
        import numpy as np
        from numba import cuda
        from numba.core.errors import NumbaPerformanceWarning

        @cuda.jit(cache=False)
        def _probe(x):
            i = cuda.grid(1)
            if i < x.shape[0]:
                x[i] = x[i] + 1.0

        arr = cuda.to_device(np.zeros(1, dtype=np.float32))
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", NumbaPerformanceWarning)
            _probe[1, 1](arr)
        cuda.synchronize()

        # Extract the PTX .version directive from the compiled kernel.
        # This is the PTX ISA version llvmlite generated — if it is higher
        # than what ptxas supports, the probe above will have already failed.
        try:
            for ptx in _probe.inspect_asm().values():
                for line in ptx.splitlines():
                    m = re.match(r"\s*\.version\s+(\S+)", line)
                    if m:
                        info.ptx_version = m.group(1)
                        break
                if info.ptx_version:
                    break
        except Exception as e:
            info.warnings.append(f"Could not extract PTX version from probe kernel: {e}")

        info.available = True

    except Exception as e:
        info.errors.append(
            f"CUDA probe kernel failed to compile or run: {e}. "
            "Check that ptxas, the CUDA driver, and the CUDA runtime are all "
            "from compatible versions. Common cause: llvmlite emits a PTX ISA "
            "version newer than the ptxas on PATH supports — verify with "
            "'ptxas --version' and compare to the PTX version logged above."
        )

    return info


def _probe_mlx_toolchain() -> MLXToolchainInfo:
    """
    Collect MLX / Metal version information and verify that a probe
    computation can run on the Metal GPU.

    Stops early if MLX is not installed (not an error — just unavailable).
    """
    info = MLXToolchainInfo(available=False)

    # ── mlx ───────────────────────────────────────────────────────────────────
    try:
        import mlx.core as mx
        info.mlx_version = mx.__version__
    except ImportError:
        return info  # mlx not installed — not an error

    # ── macOS version ─────────────────────────────────────────────────────────
    try:
        info.macos_version = platform.mac_ver()[0] or None
    except Exception:
        pass

    # ── Metal device info ─────────────────────────────────────────────────────
    try:
        device_info = mx.metal.device_info()
        info.gpu_name = device_info.get("device_name")
        info.memory_size = device_info.get("memory_size")
        raw_mv = device_info.get("metal_version")
        info.metal_version = str(raw_mv) if raw_mv is not None else None
    except Exception as e:
        info.warnings.append(f"Could not query Metal device info: {e}")

    # ── Probe computation ─────────────────────────────────────────────────────
    try:
        import mlx.core as mx
        mx.eval(mx.array([1.0, 2.0, 3.0], dtype=mx.float32) * 2.0)
        info.available = True
    except Exception as e:
        info.errors.append(f"MLX probe computation failed: {e}")

    return info


# ============================================================================ #
# Capability registry                                                           #
# ============================================================================ #


class _BackendCapabilities:
    """
    Lazy, cached detection of all available quarimo backends.

    Use the module-level ``backends`` singleton rather than instantiating this
    class directly.  Properties are evaluated at most once per session.

    Properties
    ----------
    numba : bool
        True if the ``numba`` package is importable.  Required for both the
        ``cpu-parallel`` and ``cuda`` backends.
    cuda : bool
        True if the CUDA probe kernel compiled and ran successfully.
        Implies numba is available and a compatible GPU + driver are present.
    mlx : bool
        True if the MLX probe computation ran successfully on a Metal GPU.
        Apple Silicon only; mutually exclusive with ``cuda`` in practice.
    cuda_info : CUDAToolchainInfo
        Full toolchain snapshot for the CUDA backend.
    mlx_info : MLXToolchainInfo
        Full toolchain snapshot for the MLX backend.
    """

    @cached_property
    def numba(self) -> bool:
        """True if Numba is installed (enables ``cpu-parallel`` backend)."""
        try:
            import numba  # noqa: F401
            return True
        except ImportError:
            return False

    @cached_property
    def cuda_info(self) -> CUDAToolchainInfo:
        """Full CUDA toolchain snapshot (computed once, cached)."""
        return _probe_cuda_toolchain()

    @cached_property
    def mlx_info(self) -> MLXToolchainInfo:
        """Full MLX toolchain snapshot (computed once, cached)."""
        return _probe_mlx_toolchain()

    @cached_property
    def cuda(self) -> bool:
        """True if Numba + a CUDA-capable GPU are present (enables ``cuda`` backend)."""
        return self.cuda_info.available

    @cached_property
    def mlx(self) -> bool:
        """True if MLX + Metal GPU are available (enables ``mlx`` backend, Apple Silicon)."""
        return self.mlx_info.available

    # ------------------------------------------------------------------
    # Derived helpers
    # ------------------------------------------------------------------

    def available(self) -> List[str]:
        """
        Return available backend names in ascending preference order.

        The last element is always the best (highest-performance) backend.

        Examples
        --------
        >>> backends.available()
        ['python', 'cpu-parallel', 'cuda']   # NVIDIA Linux
        >>> backends.available()
        ['python', 'cpu-parallel', 'mlx']    # Apple Silicon
        >>> backends.available()
        ['python']                           # minimal install
        """
        result = ["python"]
        if self.numba:
            result.append("cpu-parallel")
        if self.mlx:
            result.append("mlx")
        if self.cuda:
            result.append("cuda")
        return result

    def best(self) -> str:
        """Return the highest-priority available backend name."""
        return self.available()[-1]

    def resolve_for_kernel(self, kernel: str, backend: str) -> Tuple[str, Optional[str]]:
        """
        Resolve a backend for a specific kernel, with graceful fallback.

        If the resolved backend has no implementation for *kernel*, the
        next-best available backend that does is returned instead.

        Parameters
        ----------
        kernel : str
            Key in ``KERNEL_IMPLEMENTATIONS`` (e.g. ``'quartet_topology'``).
        backend : str
            Requested backend name or ``'best'``.

        Returns
        -------
        (effective, original)
            *effective* is the backend to use.  *original* is the originally
            requested backend when a fallback occurred, otherwise ``None``.
        """
        resolved = self.resolve(backend)  # raises ValueError if unavailable
        supported = KERNEL_IMPLEMENTATIONS.get(kernel, frozenset())
        if resolved in supported:
            return resolved, None
        # Fall back to the best available backend that has this kernel
        fallback = next(
            (b for b in reversed(self.available()) if b in supported),
            "python",
        )
        return fallback, resolved

    def status(self) -> List[Tuple[str, bool]]:
        """
        Return all known backends in ascending priority order with availability.

        Each entry is ``(name, is_available)``.  New backends must be added
        here so that ``log_backend_availability`` reports them automatically.

        Returns
        -------
        list[tuple[str, bool]]
            e.g. ``[('python', True), ('cpu-parallel', True), ('mlx', False), ('cuda', False)]``
        """
        return [
            ("python", True),
            ("cpu-parallel", self.numba),
            ("mlx", self.mlx),
            ("cuda", self.cuda),
        ]

    def resolve(self, backend: str) -> str:
        """
        Validate and return a concrete backend name.

        Parameters
        ----------
        backend : str
            ``'best'`` or an explicit backend name (``'python'``,
            ``'cpu-parallel'``, ``'cuda'``, ``'mlx'``).

        Returns
        -------
        str
            The resolved backend name.

        Raises
        ------
        ValueError
            If *backend* is not in ``available()``.
        """
        if backend == "best":
            return self.best()
        available = self.available()
        if backend not in available:
            raise ValueError(
                f"Backend '{backend}' not available. "
                f"Available backends: {', '.join(available)}"
            )
        return backend


# ============================================================================ #
# Module-level singleton and startup logging                                    #
# ============================================================================ #

# Module-level singleton — the single source of truth for backend availability
backends = _BackendCapabilities()


def _log_backend_status() -> None:
    """
    Log toolchain version information and any detected incompatibilities.

    Called once at module load.  Log levels:

    - DEBUG   — detailed version strings (numba, llvmlite, LLVM, driver,
                runtime, PTX, ptxas, GPU names)
    - INFO    — one-line summary of available backends
    - WARNING — non-fatal issues (e.g. ptxas not on PATH, minor version gaps)
    - CRITICAL — incompatibilities that will prevent a backend from working
                 (e.g. driver older than runtime, probe kernel failed)
    """
    avail = backends.available()
    logger.info("Available backends: %s  (best: %s)", ", ".join(avail), avail[-1])

    # ── CUDA toolchain ────────────────────────────────────────────────────────
    cuda = backends.cuda_info
    if cuda.numba_version is not None:  # numba is installed
        _fv = lambda v: f"{v[0]}.{v[1]}" if v else "unknown"
        logger.debug(
            "CUDA toolchain — numba %s | llvmlite %s | LLVM %s | "
            "driver CUDA %s | runtime CUDA %s | PTX %s",
            cuda.numba_version,
            cuda.llvmlite_version or "?",
            cuda.llvm_version or "?",
            _fv(cuda.cuda_driver_version),
            _fv(cuda.cuda_runtime_version),
            cuda.ptx_version or "? (probe not reached)",
        )
        if cuda.ptxas_path:
            logger.debug("ptxas — %s  (%s)", cuda.ptxas_path, cuda.ptxas_version or "?")
        for d in cuda.devices:
            cc = d["compute_capability"]
            logger.debug("  CUDA device: %s  (CC %d.%d)", d["name"], cc[0], cc[1])
        for w in cuda.warnings:
            logger.warning("CUDA toolchain: %s", w)
        for e in cuda.errors:
            logger.critical("CUDA toolchain: %s", e)

    # ── MLX toolchain ─────────────────────────────────────────────────────────
    mlx = backends.mlx_info
    if mlx.mlx_version is not None:  # mlx is installed
        mem_str = (
            f"{mlx.memory_size / (1024 ** 3):.0f} GB"
            if mlx.memory_size else "unknown"
        )
        logger.debug(
            "MLX toolchain — mlx %s | GPU: %s | memory: %s | Metal: %s | macOS: %s",
            mlx.mlx_version,
            mlx.gpu_name or "unknown",
            mem_str,
            mlx.metal_version or "unknown",
            mlx.macos_version or "unknown",
        )
        for w in mlx.warnings:
            logger.warning("MLX toolchain: %s", w)
        for e in mlx.errors:
            logger.critical("MLX toolchain: %s", e)


_log_backend_status()


# ============================================================================ #
# Backward-compatible public API                                                #
# (thin wrappers; prefer importing `backends` directly in new code)            #
# ============================================================================ #


def check_numba_available() -> bool:
    """Return True if Numba is installed."""
    return backends.numba


def check_cuda_available() -> Tuple[bool, bool]:
    """Return ``(numba_available, cuda_available)`` for backward compatibility."""
    return (backends.numba, backends.cuda)


def check_mlx_available() -> bool:
    """Return True if MLX with Metal GPU is available (Apple Silicon)."""
    return backends.mlx


def get_available_backends() -> List[str]:
    """Return available backend names in ascending preference order."""
    return backends.available()


def get_best_backend() -> str:
    """Return the highest-priority available backend name."""
    return backends.best()


def resolve_backend(backend: str) -> str:
    """Validate and resolve a backend name; raises ValueError if unavailable."""
    return backends.resolve(backend)


def get_backend_info() -> dict:
    """
    Return a comprehensive dict of backend availability and toolchain status.

    The ``cuda_toolchain`` and ``mlx_toolchain`` sub-dicts mirror the fields
    of ``CUDAToolchainInfo`` and ``MLXToolchainInfo`` respectively.  They are
    ``None`` when the corresponding package (numba / mlx) is not installed.
    """
    cuda = backends.cuda_info
    mlx = backends.mlx_info

    return {
        "numba_available":  backends.numba,
        "cuda_available":   backends.cuda,
        "mlx_available":    backends.mlx,
        "backends":         backends.available(),
        "best_backend":     backends.best(),
        "cuda_toolchain": {
            "numba_version":        cuda.numba_version,
            "llvmlite_version":     cuda.llvmlite_version,
            "llvm_version":         cuda.llvm_version,
            "cuda_driver_version":  cuda.cuda_driver_version,
            "cuda_runtime_version": cuda.cuda_runtime_version,
            "ptx_version":          cuda.ptx_version,
            "ptxas_path":           cuda.ptxas_path,
            "ptxas_version":        cuda.ptxas_version,
            "devices":              cuda.devices,
            "errors":               cuda.errors,
            "warnings":             cuda.warnings,
        } if cuda.numba_version is not None else None,
        "mlx_toolchain": {
            "mlx_version":   mlx.mlx_version,
            "gpu_name":      mlx.gpu_name,
            "memory_size":   mlx.memory_size,
            "metal_version": mlx.metal_version,
            "macos_version": mlx.macos_version,
            "errors":        mlx.errors,
            "warnings":      mlx.warnings,
        } if mlx.mlx_version is not None else None,
    }
